name: mensa_uniurb
description: Check what's for lunch using this beautiful app

version: 1.4.0+9

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_launcher_icons: ^0.9.0
  font_awesome_flutter: ^9.0.0-nullsafety
  http: ^0.13.0
  intl: ^0.17.0
  shared_preferences: ^2.0.3
  url_launcher: ^6.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: Noto
      fonts:
        - asset: fonts/NotoSans-Bold.ttf
        - asset: fonts/NotoSans-Regular.ttf

flutter_icons:
  android: true 
  ios: true
  image_path: "assets/icon/icon.png"
