name: mensa_uniurb
description: Check what's for lunch!

version: 1.9.0+16

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  font_awesome_flutter: ^10.8.0
  http: ^1.3.0
  shared_preferences: ^2.5.1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - img/
    - assets/icon/icon.png

  fonts:
    - family: Noto
      fonts:
        - asset: fonts/NotoSans-Bold.ttf
        - asset: fonts/NotoSans-Regular.ttf

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/icon.png"

flutter_native_splash:
  color: "#ffffff"
  image: "assets/icon/splash_icon.png"

  android_12:
    image: "assets/icon/splash_icon.png"
    color: "#ffffff"
