name: mensa_uniurb
description: Check what's for lunch!

version: 1.9.0+16

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  font_awesome_flutter: ^10.8.0
  http: ^1.3.0
  shared_preferences: ^2.5.1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: Noto
      fonts:
        - asset: fonts/NotoSans-Bold.ttf
        - asset: fonts/NotoSans-Regular.ttf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
